const TASK_TYPES = {
    CREATE_TASK:"CREATE_TASK",
    CREATE_TASK_LOADING:"CREATE_TASK_LOADING",
    CREATE_TASK_SUCCESS:"CREATE_TASK_SUCCESS",
    CREATE_TASK_ERROR:"CREATE_TASK_ERROR",
    CREATE_TASK_RESET:"CREATE_TASK_RESET",

    GET_SINGLE_SPRINT_TASK:"GET_SINGLE_SPRINT_TASK",
    GET_SINGLE_SPRINT_TASK_LOADING:"GET_SINGLE_SPRINT_TASK_LOADING",
    GET_SINGLE_SPRINT_TASK_SUCCESS:"GET_SINGLE_SPRINT_TASK_SUCCESS",
    GET_SINGLE_SPRINT_TASK_ERROR:"GET_SINGLE_SPRINT_TASK_ERROR",
    GET_SINGLE_SPRINT_TASK_RESET:"GET_SINGLE_SPRINT_TASK_RESET",
    
    GET_ALL_TASK:"GET_ALL_TASK",
    GET_ALL_TASK_LOADING:"GET_ALL_TASK_LOADING",
    GET_ALL_TASK_SUCCESS:"GET_ALL_TASK_SUCCESS",
    GET_ALL_TASK_ERROR:"GET_ALL_TASK_ERROR",
    GET_ALL_TASK_RESET:"GET_ALL_TASK_RESET",
}

export default TASK_TYPES