const TASK_TYPES = {
    CREATE_TASK:"CREATE_TASK",
    CREATE_TASK_LOADING:"CREATE_TASK_LOADING",
    CREATE_TASK_SUCCESS:"CREATE_TASK_SUCCESS",
    CREATE_TASK_ERROR:"CREATE_TASK_ERROR",
    CREATE_TASK_RESET:"CREATE_TASK_RESET",
}

export default TASK_TYPES