 const Assigntype={

    GET_ASSIGNEE:"GET_ASSIGNEE",
    GET_ASSIGNEE_LOADING:"GET_ASSIGNEE_LOADING",
    GET_ASSIGNEE_SUCCESS:"GET_ASSIGNEE_SUCCESS",
    GET_ASSIGNEE_RESET:"GET_ASSIGNEE_RESET",
    GET_ASSIGNEE_ERROR:"GET_ASSIGNEE_ERROR"

}

export default Assigntype;