const express = require('express');
const subtaskRoute = express.Router();
const subTasks = require('../controller/sub_task');
subtaskRoute.get('/', subTasks.taskdetails);
subtaskRoute.post("/getsingletask",subTasks.getSingleTaskById);
subtaskRoute.post('/addsubtask', subTasks.addSubTask);
subtaskRoute.delete("/deletetask",subTasks.deleteSubTask);
subtaskRoute.put("/updatetaskdetails/:_id",subTasks.updatetaskdetails);
subtaskRoute.put("/assigntask",subTasks.assigntaskuser);
subtaskRoute.post("/statusupdate/:taskid",subTasks.taskstatusupdate);
module.exports = subtaskRoute;