const ProjectTypes = {
    ADD_PROJECT: 'ADD_PROJECT',
    ADD_PROJECT_LOADING: 'ADD_PROJECT_LOADING',
    ADD_PROJECT_SUCCESS: 'ADD_PROJECT_SUCCESS',

    ADD_PROJECT_ERROR: 'ADD_PROJECT_ERROR',
    ADD_PROJECT_RESET: 'ADD_PROJECT_RESET',

    // get Catergory
    // GET_CATEGORY: "GET_CATEGORY",
    // GET_CATEGORY_LOADING: "GET_CATEGORY_LOADING",
    // GET_CATEGORY_SUCCESS: "GET_CATEGORY_SUCCESS",
    // GET_CATEGORY_RESET: "GET_CATEGORY_RESET",
    // GET_CATEGORY_ERROR: "GET_CATEGORY_ERROR",

    // update category types

    // UPDATE_CATEGORY: "UPDATE_CATEGORY",
    // UPDATE_CATEGORY_SUCCESS: "UPDATE_CATEGORY_SUCCESS",
    // UPDATE_CATEGORY_LOADING: "UPDATE_CATEGORY_LOADING",
    // UPDATE_CATEGORY_ERROR: "UPDATE_CATEGORY_ERROR",
    // UPDATE_CATEGORY_RESET: "UPDATE_CATEGORY_RESET",
};

export default ProjectTypes;
