const ProjectTypes = {
    ADD_PROJECT: 'ADD_PROJECT',
    ADD_PROJECT_LOADING: 'ADD_PROJECT_LOADING',
    ADD_PROJECT_SUCCESS: 'ADD_PROJECT_SUCCESS',

    ADD_PROJECT_ERROR: 'ADD_PROJECT_ERROR',
    ADD_PROJECT_RESET: 'ADD_PROJECT_RESET',

    // get Catergory
    GET_PROJECT: "GET_PROJECT",
    GET_PROJECT_LOADING: "GET_PROJECT_LOADING",
    GET_PROJECT_SUCCESS: "GET_PROJECT_SUCCESS",
    GET_PROJECT_RESET: "GET_PROJECT_RESET",
    GET_PROJECT_ERROR: "GET_PROJECT_ERROR",

    // update project details

    UPDATE_PROJECT_DETAILS: "UPDATE_PROJECT_DETAILS",
    UPDATE_PROJECT_DETAILS_LOADING: "UPDATE_PROJECT_DETAILS_LOADING",
    UPDATE_PROJECT_DETAILS_SUCCESS: "UPDATE_PROJECT_DETAILS_SUCCESS",
    
    UPDATE_PROJECT_DETAILS_ERROR: "UPDATE_PROJECT_DETAILS_ERROR",
    UPDATE_PROJECT_DETAILS_RESET: "UPDATE_PROJECT_DETAILS_RESET",
};

export default ProjectTypes;
