const MileStoneType = {


    // get Catergory
    GET_ALL_MILESTONES: "GET_ALL_MILESTONES",
    GET_ALL_MILESTONES_LOADING: "GET_ALL_MILESTONES_LOADING",
    GET_ALL_MILESTONES_SUCCESS: "GET_ALL_MILESTONES_SUCCESS",
    GET_ALL_MILESTONES_RESET: "GET_ALL_MILESTONES_RESET",
    GET_ALL_MILESTONES_ERROR: "GET_ALL_MILESTONES_ERROR",

   // delete project

   DELETE_MILE_STONE: "DELETE_MILE_STONE",
   DELETE_MILE_STONE_LOADING: "DELETE_MILE_STONE_LOADING",
   DELETE_MILE_STONE_SUCCESS: "DELETE_MILE_STONE_SUCCESS",   
   DELETE_MILE_STONE_ERROR: "DELETE_MILE_STONE_ERROR",
   DELETE_MILE_STONE_RESET: "DELETE_MILE_STONE_RESET",
    
};

export default MileStoneType;
