const Addcomment={

    ADD_COMMENT:"ADD_COMMENT",
    ADD_COMMENT_LOADING:"ADD_COMMENT_LOADING",
    ADD_COMMENT_SUCCESS:"ADD_COMMENT_SUCCESS",
    ADD_COMMENT_RESET:"ADD_COMMENT_RESET",
    ADD_COMMENT_ERROR:"ADD_COMMENT_ERROR",

    
    // GET_COMMENT:"GET_COMMENT",
    // GET_COMMENT_LOADING:"GET_COMMENT_LOADING",
    // GET_COMMENT_SUCCESS:"GET_COMMENT_SUCCESS",
    // GET_COMMENT_RESET:"GET_COMMENT_RESET",
    // GET_COMMENT_ERROR:"GET_COMMENT_ERROR"

}

export default Addcomment;