const Addcomment={

    ADD_COMMENT:"ADD_COMMENT",
    ADD_COMMENT_LOADING:"ADD_COMMENT_LOADING",
    ADD_COMMENT_SUCCESS:"ADD_COMMENT_SUCCESS",
    ADD_COMMENT_RESET:"ADD_COMMENT_RESET",
    ADD_COMMENT_ERROR:"ADD_COMMENT_ERROR",


    DELETE_COMMENT:"DELETE_COMMENT",
    DELETE_COMMENT_LOADING:"DELETE_COMMENT_LOADING",
    DELETE_COMMENT_SUCCESS:"DELETE_COMMENT_SUCCESS",
    DELETE_COMMENT_RESET:"DELETE_COMMENT_RESET",
    DELETE_COMMENT_ERROR:"DELETE_COMMENT_ERROR",
    

    UPDATE_COMMENT:"UPDATE_COMMENT",
    UPDATE_COMMENT_LOADING:"UPDATE_COMMENT_LOADING",
    UPDATE_COMMENT_SUCCESS:"UPDATE_COMMENT_SUCCESS",
    UPDATE_COMMENT_RESET:"UPDATE_COMMENT_RESET",
    UPDATE_COMMENT_ERROR:"UPDATE_COMMENT_ERROR",

   GET_HISTORY:"GET_HISTORY",
   GET_HISTORY_LOADING:"GET_HISTORY_LOADING",
   GET_HISTORY_SUCCESS:"GET_HISTORY_SUCCESS",
   GET_HISTORY_RESET:"GET_HISTORY_RESET",
   GET_HISTORY_ERROR:"GET_HISTORY_ERROR"


   



    // GET_COMMENT:"GET_COMMENT",
    // GET_COMMENT_LOADING:"GET_COMMENT_LOADING",
    // GET_COMMENT_SUCCESS:"GET_COMMENT_SUCCESS",
    // GET_COMMENT_RESET:"GET_COMMENT_RESET",
    // GET_COMMENT_ERROR:"GET_COMMENT_ERROR"

}

export default Addcomment;