const TECHNOLOGY_TYPES = {
    CREATE_TECHNOLOGY:"CREATE_TECHNOLOGY",
    CREATE_TECHNOLOGY_LOADING:"CREATE_TECHNOLOGY_LOADING",
    CREATE_TECHNOLOGY_SUCCESS:"CREATE_TECHNOLOGY_SUCCESS",
    CREATE_TECHNOLOGY_ERROR:"CREATE_TECHNOLOGY_ERROR",
    CREATE_TECHNOLOGY_RESET:"CREATE_TECHNOLOGY_RESET",

    GET_TECHNOLOGY:"GET_TECHNOLOGY",
    GET_TECHNOLOGY_LOADING:"GET_TECHNOLOGY_LOADING",
    GET_TECHNOLOGY_SUCCESS:"GET_TECHNOLOGY_SUCCESS",
    GET_TECHNOLOGY_ERROR:"GET_TECHNOLOGY_ERROR",
    GET_TECHNOLOGY_RESET:"GET_TECHNOLOGY_RESET",

    UPDATE_TECHNOLOGY:"UPDATE_TECHNOLOGY",
    UPDATE_TECHNOLOGY_LOADING:"UPDATE_TECHNOLOGY_LOADING",
    UPDATE_TECHNOLOGY_SUCCESS:"UPDATE_TECHNOLOGY_SUCCESS",
    UPDATE_TECHNOLOGY_ERROR:"UPDATE_TECHNOLOGY_ERROR",
    UPDATE_TECHNOLOGY_RESET:"UPDATE_TECHNOLOGY_RESET",
}

export default TECHNOLOGY_TYPES