const SUMMARY_TYPES = {
  
    GET_TASK_SUMMARY:"GET_TASK_SUMMARY",
    GET_TASK_SUMMARY_LOADING:"GET_TASK_SUMMARY_LOADING",
    GET_TASK_SUMMARY_SUCCESS:"GET_TASK_SUMMARY_SUCCESS",
    GET_TASK_SUMMARY_ERROR:"GET_TASK_SUMMARY_ERROR",
    GET_TASK_SUMMARY_RESET:"GET_TASK_SUMMARY_RESET",

    GET_PRIORITY_GRAPH:"GET_PRIORITY_GRAPH",
    GET_PRIORITY_GRAPH_LOADING:" GET_PRIORITY_GRAPH_LOADING",
    GET_PRIORITY_GRAPH_SUCCESS:" GET_PRIORITY_GRAPH_SUCCESS",
    GET_PRIORITY_GRAPH_ERROR:" GET_PRIORITY_GRAPH_ERROR",
    GET_PRIORITY_GRAPH_RESET:" GET_PRIORITY_GRAPH_RESET",
}

export default SUMMARY_TYPES