const USERS_TYPES = {
    GET_ALL_USERS:"GET_ALL_USERS",
    GET_ALL_USERS_LOADING:"GET_ALL_USERS_LOADING",
    GET_ALL_USERS_SUCCESS:"GET_ALL_USERS_SUCCESS",
    GET_ALL_USERS_ERROR:"GET_ALL_USERS_ERROR",
    GET_ALL_USERS_RESET:"GET_ALL_USERS_RESET",

    DELETE_USER:"GET_DELETE_USER",
    GET_DELETE_USER_LOADING:"GET_DELETE_USER_LOADING",
    GET_DELETE_USER_SUCCESS:"GET_DELETE_USER_SUCCESS",
    GET_DELETE_USER_ERROR:"GET_DELETE_USER_ERROR",
    GET_DELETE_USER_RESET:"GET_DELETE_USER_RESET",
}

export default USERS_TYPES